# Generated by Django 5.2.3 on 2025-06-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_location',
            field=models.CharField(blank=True, max_length=100, verbose_name="Where I'm participating from"),
        ),
        migrations.AddField(
            model_name='profile',
            name='motto',
            field=models.CharField(blank=True, max_length=255, verbose_name='My Motto'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, verbose_name='About Me'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='website',
            field=models.URLField(blank=True, verbose_name='Website or Portfolio'),
        ),
    ]
